export const GET_SIGNATURE_REQUEST = 'GET_SIGNATURE_REQUEST';
export const GET_SIGNATURE_SUCCESS = 'GET_SIGNATURE_SUCCESS';
export const GET_SIGNATURE_FAILURE = 'GET_SIGNATURE_FAILURE';

export const SCAN_QRCODE_REQUEST = 'SCAN_QRCODE_REQUEST';
export const SCAN_QRCODE_SUCCESS = 'SCAN_QRCODE_SUCCESS';
export const SCAN_QRCODE_FAILURE = 'SCAN_QRCODE_FAILURE';
